### ISSUE TITLE
always return nil when call objc_getAssociatedObject(view, kDragSourceKey) 

### ISSUE THREAD

**Issue by samye1976** [nevyn/CoreDragon#10]
if I long press the image, the lldb debug says "Cancelling drag operation because no item was put on pasteboard", and further lock to the method "- (SPDragSource*)sourceUnderLocation:(CGPoint)locationInWindow" in DragonController.m when calling "source = objc_getAssociatedObject(view, kDragSourceKey);" which always return nil to source.

and I did notice that view and kDragSourceKey have value.

your suggestion is appreciated

**Comment by samye1976** [comment]
this issue have been resolved due to I have not check enable interaction in UIimageView main storyboard

**Comment by nevyn** [comment]
Hey @samye1976, sorry it took so long. Yeah, the "enable interaction" thingie is tricky, I run into that one often! I should make a note in the readme or something.

**Comment by nevyn** [comment]
@samye1976 here you go :) https://github.com/nevyn/CoreDragon/wiki#i-cant-start-dragging-my-image-view

Thanks for the bug report!

**Comment by jcampbell05** [comment]
@nevyn  If we register it to be dragged, could we not enable userInteractionEnabled ?
