### ISSUE TITLE
Minimum target 9.1?

### ISSUE THREAD

**Issue by benjdum59** [nevyn/CoreDragon#9]
Hi, thanks for this great pod. I'm wondering why you set minimum target to 9.1 in podspec? It seems to work on 8.4.

**Comment by nevyn** [comment]
@benjdum59 Oh, I was only considering the multitasking part of CoreDragon when I set that requirement. My bad, I will make that part a runtime check and decrease the version requirement. Thanks for noticing!

**Comment by nevyn** [comment]
Fixed!

**Comment by nevyn** [comment]
Thanks for the report @benjdum59 :)
